apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: app
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  DB_PASSWORD: cG9zdGdyZXM=  # Base64 encoded 'postgres'
