apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: db
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  POSTGRES_DB: bWVuc2FnZWVkYg==  # Base64 encoded 'mensagensdb'

