apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: amelus99/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://backend:5000/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None

